### ISSUE TITLE
HTTP Response Code not set for 404

### ISSUE THREAD

**Issue by jkns** [awbush/lightvc#9] opened 2015-10-05 08:34 UTC
Although the 404 view is displayed when you enter a page that does not exist, it returns a 200 response code.

I've added ```http_response_code($errorNum);``` to ```/controllers/error.php``` but not sure if there is a better way? I can see the ```loadPageNotFound()``` method but it's not called from anywhere.

**Comment by awbush** [comment] 2015-10-05 13:20
Good catch. I think `http_response_code` should go in `sendHttpStatusHeader`, however. That looks like a PHP 5.4+ only function, though. Perhaps the issue is just with the `HTTP 1.1` vs `HTTP/1.1` mentioned in https://github.com/awbush/lightvc/issues/10?

(`loadPageNotFound()` is a connivence method for users, that's why it's not called in the core code.)

**Comment by jkns** [comment] 2015-10-05 14:17
Ah cool. I get it now. I've created a pull request.

**Comment by awbush** [comment] 2015-10-05 15:18
Resolved by #11

**Comment by awbush** [comment] 2015-10-05 15:18
Resolved by #11

**Closed by awbush** 2015-10-05 15:18 UTC
